name: Frontend CI/CD - version 1

on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['main', 'develop']

jobs:
  build-and-test:
    name: Building and testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use cached node_modules
        uses: actions/cache@v3.3.0
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies with frozen-lockfile
        run: yarn install --frozen-lockfile

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - uses: actions/checkout@v3
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: Ae6UkAZsUZ6xDT2dcdG2eB5e # Required
          vercel-args: '--prod' #Optional
          vercel-org-id: fxTWh9kHrfV9hIZepvP3qzXk #Required
          vercel-project-id: prj_9tWdiRYSLTbk3NfQBiCq6ZrSWmsH #Required
