name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Where to publish (release or prod)?'
        required: true
        default: release

jobs:
  release:
    name: Deploy to release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: Ae6UkAZsUZ6xDT2dcdG2eB5e # Required
          vercel-org-id: fxTWh9kHrfV9hIZepvP3qzXk #Required
          vercel-project-id: prj_9tWdiRYSLTbk3NfQBiCq6ZrSWmsH #Required
  
  prod:
    if: github.event.inputs.releaseType == 'prod'
    name: Deploy to prod
    runs-on: ubuntu-latest
    needs: [staging]
    steps:
      - uses: actions/checkout@v3
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: Ae6UkAZsUZ6xDT2dcdG2eB5e # Required
          vercel-org-id: fxTWh9kHrfV9hIZepvP3qzXk #Required
          vercel-project-id: prj_9tWdiRYSLTbk3NfQBiCq6ZrSWmsH #Required